export const MESSAGE_CODES = {
    SUCCESS: "success",
    NOT_FOUND: "not_found",
    INVALID_REQUEST: "invalid_request",
    INTERNAL_SERVER_ERROR: "internal_server_error",
    NOT_IMPLEMENT_YET: "not_implement_yet",
    BAD_REQUEST: "bad_request",
    UNAUTHORIZED: "unauthorized",
    REQUEST_TIMEOUT: "request_timeout",
    T0O_MANY_REQUESTS: "too_many_requests",
    SERVICE_UNAVAILABLE: "service_unavailable",
    TRANSACTION_ALREADY_EXISTS: "transaction_already_exists",
    TRANSACTION_NOT_FOUND: "transaction_not_found",
    INVALID_TRANSACTION: "invalid_transaction",
    ITEM_NOT_FOUND: "item_not_found",
    INVALID_TRANSACTION_HASH: "invalid_transaction_hash",
    TRANSACTION_ALREADY_VALIDATED: "transaction_already_validated",
    INVALID_NFT_ITEM: "invalid_nft_item",
    ALL_TOKEN_ARE_CLAIMED: "all_token_are_claimed",
    TON_PROOF_REQUIRED: "ton_proof_required",
    TON_PROOF_INVALID: "ton_proof_invalid",
    TON_PROOF_EXPIRED: "ton_proof_expired",
    YOU_ARE_NOT_ELIGIBLE: "you_are_not_eligible",
    AIRDROP_ALREADY_CLAIMED: "airdrop_already_claimed"
}
